# Generated by Django 5.1.4 on 2025-01-09 10:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_groups_alter_user_user_permissions'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
