# Generated by Django 5.1.4 on 2025-01-09 19:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_alter_event_created_by'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='created_by',
            new_name='organizer',
        ),
    ]
