# Generated by Django 5.1.4 on 2025-01-10 08:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_rename_created_by_event_organizer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='organizer',
            new_name='organizer1',
        ),
    ]
