# Generated by Django 5.1.4 on 2025-01-11 17:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0009_event_attendees_count_attendee_waitlist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendee',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendees', to='events.event'),
        ),
        migrations.AlterField(
            model_name='waitlist',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='waitlist', to='events.event'),
        ),
        migrations.AlterUniqueTogether(
            name='attendee',
            unique_together={('email', 'event')},
        ),
        migrations.AlterUniqueTogether(
            name='waitlist',
            unique_together={('email', 'event')},
        ),
    ]
